### ISSUE TITLE
Hi from the single-spa core team

### ISSUE THREAD

**Issue by joeldenning** [umijs/qiankun#337]
Hi there 👋

I am one of the members of the single-spa core team. We appreciate the work you've done here with qiankun and for helping popularize single-spa.

I wanted to reach out just to introduce myself and get to know you. Also to let you know that I would be happy to collaborate with you on any of the following:

- Discuss any of the needs of the qiankun community and how changes to single-spa could help with that.
- Upgrading qiankun to [single-spa@5.0.0](https://github.com/single-spa/single-spa/releases/tag/v5.0.0)
- Translation of single-spa documentation to Chinese. We have a team working on it and would love more contributors. https://zh-hans.single-spa.js.org/languages/
- Discuss Angular 9 support. [single-spa-angular](https://github.com/single-spa/single-spa-angular) is still missing a couple things for Angular 9 support. I'd love to hear how you are successfully integrating Angular into qiankun.

> An implementation of Micro Frontends, based on single-spa, but made it production-ready.

^ Reading this hurt me 😄.

One thing I'd like collaborate on with you is to compare and contrast qiankun to the [single-spa recommended setup](https://single-spa.js.org/docs/recommended-setup). My guess is that qiankun and the recommended setup have both solved similar problems and could learn from each other on how to make microfrontends better. I hope that it is okay that [I linked to qiankun](https://single-spa.js.org/docs/recommended-setup#alternatives) as an alternative to the recommended setup - my intent is to support what you are doing with qiankun.

Looking forward to hearing from you.

**Comment by kuitos** [comment]
Hi @joeldenning 

Very appreciate the great work what you have done with single-spa and systemjs, and the recommendation on single-spa offical site. To be honest I had notice that for several days, sorry for our late thanks😄

As we wrote on homepage, single-spa is an very elegant library who implements micro-frontends in our team opinion. Standing on the shoulders of giants makes we growing fast, that is also the reason why qiankun can be noticed in a short time. Salute all the single-spa core team member🤝

> > An implementation of Micro Frontends, based on single-spa, but made it production-ready.
>
> ^ Reading this hurt me 😄.

I am sorry for that if you are serious😄

In our practical scenario, integration compatibility with many legacy applications is required, and the number of subapplications is considerable, the isolation between applications becomes especially important. Therefore, we encapsulated js sandbox and CSS isolation mechanism on the basis of single-spa, as well as some application access way that we thought were closer to our scenario, which is why we thought using single-spa alone could not meet the requirements of the production environment. If that words offends the single-spa core team, feel free to let us know and we can delete it at any time😀

There is not much difference between the use of qiankun and single-spa recommend setup imo, except that we're almost entirely based on webpack. We will focus on reviewing the [single-spa recommended setup](https://single-spa.js.org/docs/recommended-setup) recently to see if there are anything that can be improved together.

> Upgrading qiankun to [single-spa@5.0.0](https://github.com/single-spa/single-spa/releases/tag/v5.0.0)

We are working on the next major version of qiankun, and it had upgraded to single-spa 5.0.

> Discuss Angular 9 support. [single-spa-angular](https://github.com/single-spa/single-spa-angular) is still missing a couple things for Angular 9 support. I'd love to hear how you are successfully integrating Angular into qiankun.

@Deturium You could look into this section.

> Discuss any of the needs of the qiankun community and how changes to single-spa could help with that.

That is awesome. To be honest we had contributed some pr to fix issues of single-spa, if you have the impression with my github id😀

We could keep in touch on single-spa issues or the more efficient approach if you have a recommendation.

**Comment by Deturium** [comment]
haha, to be honest, I'm not familar with Angular. 

As you known, the integrating Angular into quankun is still having some problems. I only build demo with the help from single-spa-angular successfully. I'm also on the way.  

：）

**Comment by joeldenning** [comment]
> I am sorry for that if you are serious😄

> If that words offends the single-spa core team, feel free to let us know and we can delete it at any time

Do not worry, I was not offended or saddened by it. I am glad that you have found single-spa useful. I believe that is production ready, even without qiankun. But I agree that additional structure is helpful (such as the structure provided by The Recommended Setup or qiankun). You are of course free to put whatever you'd like into the readme for qiankun.

> We are working on the next major version of qiankun, and it had upgraded to single-spa 5.0.

Great! One other thing - we have a notable feature coming in the next week that will add support for easier "activity functions":

```js
// registerApplication will soon work with an object as arguments.
// Also, 'activeWhen' can be a string.
// See https://github.com/single-spa/single-spa/pull/497
registerApplication({
  name: 'app1',
  app: app1,
  activeWhen: ['/app1', '/other-route']
})
```

> To be honest we had contributed some pr to fix issues of single-spa, if you have the impression with my github id

Yes, I recognize your github username from previous PRs! Thanks for your contributions to single-spa in the past.

> As you known, the integrating Angular into quankun is still having some problems. I only build demo with the help from single-spa-angular successfully. I'm also on the way.

Ah yes that's where we are, too. single-spa + angular is always fairly difficult.

> We could keep in touch on single-spa issues or the more efficient approach if you have a recommendation.

The [single-spa slack workspace](https://join.slack.com/t/single-spa/shared_invite/enQtODAwNTIyMzc4OTE1LWUxMTUwY2M1MTY0ZGMzOTUzMGNkMzI1NzRiYzYwOWM1MTEzZDM1NDAyNWM3ZmViOTAzZThkMDcwMWZmNTFmMWQ) has 1,300 members and is the easiest way to communicate with me. I am responsive on Slack. Alternatively, I have WeChat and would be willing to share my phone number (privately) to you there if that is easier for you.

I am closing this issue, but look forward to collaborating more with you in the future.
